pipeline {
    agent any
    tools {
        maven 'Maven-3.9.9' // Użyj nazwy skonfigurowanej w Jenkins Global Tool Configuration
    }
    stages {
        stage("Clean Up") {
            steps {
                deleteDir()
            }
        }
        stage("Clone Repo") {
            steps {
                sh "git clone https://github.com/jenkins-docs/simple-java-maven-app.git"
            }
        }
        stage("Build") {
            steps {
                dir("simple-java-maven-app") {
                    sh "mvn clean install"
                }
            }
        }
        stage("Complete") {
            steps {
                echo 'Job Complete!'
            }
        }
    }
}
