pipeline {
    agent any
    environment {
        MAVEN_HOME = "/usr/share/maven" // Ścieżka do poprawnej wersji Maven
        PATH = "${MAVEN_HOME}/bin:${env.PATH}" // Upewnienie się, że używana jest właściwa wersja Maven
    }
    stages {
        stage("Clean Up") {
            steps {
                deleteDir()
            }
        }
        stage("Clone Repo") {
            steps {
                sh "git clone https://github.com/jenkins-docs/simple-java-maven-app.git"
            }
        }
        stage("Set Up Maven") {
            steps {
                script {
                    sh 'mvn -version'
                }
            }
        }
        stage("Build") {
            steps {
                dir("simple-java-maven-app") {
                    sh "mvn clean install"
                }
            }
        }
        stage("Test") {
            steps {
                dir("simple-java-maven-app") {
                    sh "mvn test"
                }
            }
        }
    }
}
